name: app_nckh
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  video_thumbnail: ^0.5.3
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  video_player: ^2.6.1
  chewie: ^1.5.0
  google_sign_in: ^6.1.0
  flutter_secure_storage: ^8.1.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  camera: ^0.11.0+2
  flutter_tts: ^3.8.5
  http_parser: ^4.0.2
  wakelock_plus: ^1.1.1
  url_launcher: ^6.3.0
  app_links: ^6.3.2
  network_info_plus: ^6.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/google.png
    - assets/img/facebook.png
    - assets/img/github.png
    - assets/img/lock.png
    - assets/img/logoMobile.png
    - assets/img/logoVietNam.png
    - assets/img/signSmartLogo.png
    - assets/img/SignSmart_Logo_TrongSuot.png
